#!/usr/bin/env bash

#read in variables
#读取公共变量
source common_variables.sh

#set lengths and offsets. These are the final ones which you will use for any DE analysis.
#Use the plots generated by the periodicity and offset scripts to decide what values to set these at
#设置最终用于差异表达分析的 read 长度和 offset；具体取值应根据 periodicity 和 offset 脚本生成的图形来决定。

lengths='27,28,29,30,31,32'
offsets='12,12,12,12,13,13'

#run counting script to generate <.counts> files
#运行 counting_script.py 生成最终的 <.counts> 文件

for filename in $RPF_filenames
do
counting_script.py -bam $BAM_dir/${filename}_pc_deduplicated_sorted.bam -fasta $most_abundant_fasta -len $lengths -offset $offsets -out_file ${filename}_pc_final.counts -out_dir $counts_dir &
done
wait
